### ISSUE TITLE
legendItems.enter(...).call is not a function

### ISSUE THREAD

**Issue by joaogarin** [n3-charts/line-chart#475]
Hello,

I am running into some errors in getting line charts to work.  I am using angular1.5, I have checked the codepen with 1.5 and works fine.

But for some reason I get some errors : 

```javascript
app.js:137 TypeError: legendItems.enter(...).call is not a function
    at Legend.update (app.js:11735)
    at EventManager.t (app.js:10240)
    at EventManager.trigger (app.js:10888)
    at updateAll (app.js:12989)
    at m.$digest (app.js:162)
    at m.$apply (app.js:165)
```

I am copying the data and options from http://n3-charts.github.io/line-chart/#/examples#column_series

Any ideas?

Best regards
Joao Garin

**Comment by joaogarin** [comment]
Will close this issue. Working with version 3.5.15 of d3.

Was using version 3.1
